/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Package;

import objects.Request;
import objects.Response;
import java.awt.Color;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniela
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    
    String MID="127.0.0.1";
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImgLog = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Msage_Error = new javax.swing.JLabel();
        Txt_Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setResizable(false);

        ImgLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login_Img.png"))); // NOI18N

        TxtUser.setToolTipText("");
        TxtUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalinga", 1, 14))); // NOI18N
        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Kalinga", 1, 16)); // NOI18N
        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Msage_Error.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        Msage_Error.setForeground(new java.awt.Color(255, 0, 0));
        Msage_Error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Txt_Password.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kalinga", 1, 14))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addComponent(ImgLog)
                        .addComponent(Msage_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(Txt_Password))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(ImgLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Msage_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
//        String user = TxtUser.getText();
//        String password = Txt_Password.getText();
//        
//        String queryMod = "SELECT * FROM moderator WHERE UserName like '" + user + "'";
//        try{
//            //PreparedStatement ps = conn.prepareStatement(query); 
//            Statement s = conn.createStatement();
//            ResultSet rs = s.executeQuery (queryMod);
//            //Se obtiene la información de la tabla
//            //prepareTable(rs);
//            if (rs.next()){
//                System.out.println("Moderator: " + rs.getString("UserName"));
//                System.out.println("Password: " + rs.getString("Password"));
//                Datos data = new Datos();
//                data.setVisible(true);
//                this.setVisible(false);
//            }else{
//                Msage_Error.setText("Incorrect username or password");
//            }
//            
//            System.out.println("Consulta finalizada");
//            
//        }catch(SQLException ex){
//            ex.printStackTrace();
//        }


    try {
            Socket sck=new Socket(MID,6986);
            ObjectOutputStream out= new ObjectOutputStream(sck.getOutputStream());
            
            SHA256 comd = new SHA256("Login"); 
            ArrayList<String> sender = new ArrayList<>();
            
            sender.add(this.TxtUser.getText());
            sender.add(new String(this.Txt_Password.getPassword()));
            
            Request req=new Request(comd.getSha(),(Object)sender);
            out.writeObject(req);
            ObjectInputStream in = new ObjectInputStream(sck.getInputStream());
            Response response=(Response)in.readObject();
            
            if (response.getCode()==200) {
                MenuAdm data = new MenuAdm();
                data.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
                this.TxtUser.setText("");
                this.Txt_Password.setText("");
                
            }
            
        } catch (IOException ex) {
           JOptionPane.showMessageDialog(this, "Ocurrio un error en el login, intentelo de nuevo.");
        } catch (NoSuchAlgorithmException ex) {
           JOptionPane.showMessageDialog(this, "Ocurrio un error en el login, llame al tecnico.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error en el login, llame al tecnico.");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgLog;
    private javax.swing.JLabel Msage_Error;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JPasswordField Txt_Password;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
