/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ce;

import java.awt.Color;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.MalformedURLException;
import java.net.Socket;
import java.net.URL;
import java.nio.file.Paths;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.util.regex.*;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import objects.Candidates;
import objects.*;

/**
 *
 * @author Tempori
 */
public class CE extends javax.swing.JFrame {
    
    /**
     * Creates new form CE
     */
    private String cel;
    String MID="127.0.0.1";
    public CE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to the 2019 vote with");

        jTextField1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextField1.setText("FDASFD45645645H789");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Elector Key:");

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please verify your Identity");

        jLabel6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel6FocusGained(evt);
            }
        });
        jLabel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel6KeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Put your finger with the one you registered on the fingerprint sensor");

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Secret:");

        jPasswordField1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 100)));

        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(24, 24, 24)))
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            this.getContentPane().setBackground(new Color(70, 73, 75));
            jLabel1.setForeground(new Color(197,197,197));
            jLabel2.setForeground(new Color(197,197,197));
            jLabel3.setForeground(new Color(197,197,197));
            jLabel4.setForeground(new Color(197,197,197));
            jLabel5.setForeground(new Color(197,197,197));
            jLabel6.setForeground(new Color(197,197,197));
            jLabel7.setForeground(new Color(197,197,197));
            jLabel8.setForeground(new Color(197,197,197));
            jTextField1.setForeground(new Color(197,197,197));
            jTextField1.setBackground(new Color(79,83,84));
            jPasswordField1.setForeground(new Color(197,197,197));
            jPasswordField1.setBackground(new Color(79,83,84));
            
            jLabel7.setVisible(false);
            BufferedImage logo1 = ImageIO.read(new File("img/title.png"));
            BufferedImage logo2= ImageIO.read(new File("img/logo.png"));
            ImageIcon icon=new ImageIcon(logo1);
            jLabel4.setIcon(new ImageIcon(icon.getImage().getScaledInstance(169, 67, Image.SCALE_DEFAULT)));
            icon= new ImageIcon(logo2);
            jLabel5.setIcon(new ImageIcon(icon.getImage().getScaledInstance(63, 67, Image.SCALE_DEFAULT)));
        } catch (IOException ex) {
            Logger.getLogger(CE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10) {
            String ceText=jTextField1.getText();
            if (ceText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter your Elector Key.");
                jTextField1.requestFocus();                
                jTextField1.setText("");
                return;
            }
            Pattern p=Pattern.compile("^[A-Z]{6}[0-9]{8}[A-Z]{1}[0-9]{3}$");
            Matcher ce = p.matcher(ceText);
            if (ce.matches()) {
                try {
                    ce.SHA256 sha=new ce.SHA256(ceText);
                    this.cel=sha.getSha();
                    System.out.println("Hash de clave de elector H(CEL):"+this.cel);
                    jTextField1.setText("");
                } catch (NoSuchAlgorithmException ex) {
                    jTextField1.setText("");
                    Logger.getLogger(CE.class.getName()).log(Level.SEVERE, null, ex);
                }                
                displayFingerPrintInput();
            }else{
                JOptionPane.showMessageDialog(this, "The Elector key format is not valid.");
                jTextField1.requestFocus();
                jTextField1.setText("");
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jLabel6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel6KeyPressed
    }//GEN-LAST:event_jLabel6KeyPressed

    private void jLabel6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel6FocusGained
    }//GEN-LAST:event_jLabel6FocusGained

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    }//GEN-LAST:event_formMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ceText=jTextField1.getText();
        String heText=new String(this.jPasswordField1.getPassword());
        
            if (ceText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter your Elector Key.");
                jTextField1.requestFocus();                
                jTextField1.setText("");
                return;
            }
            if (heText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter your Secret.");
                jPasswordField1.requestFocus();                
                jPasswordField1.setText("");
                return;
            }
            Pattern p=Pattern.compile("^[A-Z]{6}[0-9]{8}[A-Z]{1}[0-9]{3}$");
            Matcher ce = p.matcher(ceText);
            if (ce.matches()) {
                try {
                    ce.SHA256 sha=new ce.SHA256(ceText);
                    this.cel=sha.getSha();
                    SHA256 cesha= new SHA256(heText);
                    
                    System.out.println("Hash de clave de elector H(CEL):"+this.cel);
                    jTextField1.setText("");
                    jPasswordField1.setText("");
                    validate(cesha.getSha());
                } catch (NoSuchAlgorithmException ex) {
                    jTextField1.setText("");
                    Logger.getLogger(CE.class.getName()).log(Level.SEVERE, null, ex);
                }                
//                displayFingerPrintInput();
            }else{
                JOptionPane.showMessageDialog(this, "The Elector key format is not valid.");
                jTextField1.requestFocus();
                jTextField1.setText("");
            }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void closeCE(){
        this.dispose();
    }
    
    private void validate(String fingerprint){
        try { 
            Socket sck=new Socket(MID,6986);
            ObjectOutputStream out= new ObjectOutputStream(sck.getOutputStream());
            
            SHA256 comd = new SHA256("Verify"); 
            SHA256 vstring=new SHA256(this.cel+fingerprint);
            ArrayList<String> sender = new ArrayList<>();
            sender.add(vstring.getSha());
            
            Request req=new Request(comd.getSha(),(Object)sender);
            out.writeObject(req);
            ObjectInputStream in = new ObjectInputStream(sck.getInputStream());
            Response response=(Response)in.readObject();
            if (response.getCode()==200) {
                VOTE go=new VOTE(fingerprint,vstring.getSha());
                go.setVisible(true);
                closeCE();
            }else{
                JOptionPane.showMessageDialog(this, response.getMessage());
                this.cel="";
                jTextField1.requestFocus();
                jTextField1.setText("");
                jLabel7.setVisible(false);
                jLabel6.setVisible(false);
                jLabel3.setVisible(true);
                jTextField1.setVisible(true);
            }
            
        } catch (IOException ex) {
            Logger.getLogger(CE.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ocurrio un error durante la autenticacion, por favor llame a un moderador");
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(CE.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ocurrio un error durante la autenticacion, por favor llame a un moderador");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CE.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ocurrio un error durante la autenticacion, por favor llame a un moderador");
        }
    }
    
    private void  displayFingerPrintInput(){
        
        try {
            jLabel3.setVisible(false);
            jTextField1.setVisible(false);
            URL imageURL = Paths.get("img/fingerprint.gif").toUri().toURL();
            Icon icon=new ImageIcon(new ImageIcon(imageURL).getImage().getScaledInstance(94, 96, Image.SCALE_DEFAULT));
            jLabel6.setIcon(icon);
            
            jLabel6.addMouseListener(new MouseAdapter()  
            {
                @Override
                public void mouseClicked(MouseEvent e)
                {                   
                    try {
                        SHA256 sha = new SHA256("123456789");            
                        validate(sha.getSha());
                        System.out.println("Hash huella digital H(HD): "+sha.getSha());
//                      closeCE();
                    } catch (NoSuchAlgorithmException ex) {
                        Logger.getLogger(CE.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            
            jLabel7.setVisible(true);
            jLabel6.setVisible(true);
            //hilo escucha lector huella
//            Runnable runnable =() -> { getCandidates(); };
//            Thread thread = new Thread(runnable);
//            thread.start();

        } catch (MalformedURLException ex) {
            Logger.getLogger(CE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CE().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
